#PP 2.0

Finegoldia_magna_BVS033A4                       AA-AGAAGGUGUCCCACUACCUAUAU--CAAAGGUGAAACAUU
Eubacterium_saburreum_DSM_3986                  AA-AGAAGGUGUCUCACUACCUAUAUCCCAAAGGUGAAGCAUU
Fusobacterium_sp._3_1_5R                        -A-UUCAGGUGUUCCACCACCUUUAAAUGAAGCAGUUAUAA--
Fusobacterium_sp._4_1_13                        -A-UUCAGGUGUUCCACCACCUCAAAAUGAAGCAGUUUUAA--
Leptotrichia_goodfellowii_F0264                 -A-UUCGGGUGUUCCACCACCUUUAAGUGAAGGGACUAUAA--
Fusobacterium_sp._D12                           AA-UUCAGGUGUUCCACCACCUUAAAAUGAAGCAGUUAU-A--
Clostridium_cellulovorans_743B                  -A-UUCAGGUGAGGUCCUACCAUACAGUGGAC--AAUAAAA--
Pectobacterium_atrosepticum_SCRI1039            -A-UUCAGGUGAUUUGCUACCUUUAAGUGCAG---CUAGAA--
Haemophilus_parasuis_SH0165                     AU-AUGUGGUGAA-CGCUACCAUUAAAGUGCGAUGU-------
Clostridium_phage_D-1873                        AA-AGUCAGUGAGCCUCCACUGUAUAAGCGAGGAGCU-AA---
Clostridium_botulinum_BKT015925                 AA-AGUCAGUGAACCUCCACUGUAUAAGCGAGGAGCUAAA---
Bacillus_cereus_Rock_1-15                       AA-AUUUGGAGAGUCCAUGCCG--UAAGUUGGGACCG-AU---
Eubacterium_rectale_DSM_17629                   AAUAUUCGGAGAGUCACUACCGU-UAAGUGUGAGAUG-AA---
Eubacterium_yurii_subsp._margaretiae_ATCC_43715 AAGAGUAGGAGAACCCGAGCCUU-AUAAGUGGGAGUU-AA---
Fusobacterium_ulcerans_ATCC_49185               AAAAGCG-GUGUACCCUACCAU--CAAGUG-GGAGUUAA----
Peptoniphilus_duerdenii_ATCC_BAA-1640           AAAAGCG-GUGUACGCAGCCAU--AAAAUG-CGAACUAA----
Lactobacillus_gasseri_JV-V03                    AAAGACG-GUGUUUCCCAGCCA--CAAGUGAGAAUCGAAU---
Lactobacillus_jensenii_208-1                    AAAGAGGAGUGUAUCUCAGCUC--UAAGUGAGAAUUA------
Veillonella_parvula_ACS-068-V-Sch12             A--GAGCGGUAAAUCGCCACCA--UAAGAGCGAAACAAAA---

#END

#SECTION BASEPAIRS

#BPCUT 0.0005

20 28 1.02e-3
7 22 9.79e-3
26 37 6.50e-4
15 32 0.0044
9 20 0.0455
17 30 3.13e-3
8 21 0.0187
16 31 8.01e-4
11 18 6.69e-3
18 29 6.04e-4
14 33 3.08e-3
10 19 0.0233
9 36 5.98e-4
11 36 6.56e-4

#END
